#cmakedefine01 HAVE_POWL
#cmakedefine01 HAVE_IEEE_754
#cmakedefine01 HAVE_SYS_TIME_H
#cmakedefine01 HAVE_SYS_RESOURCE_H
#cmakedefine01 HAVE_GETRUSAGE
#cmakedefine01 HAVE_GETRLIMIT
#cmakedefine01 HAVE_UNISTD_H
#cmakedefine01 HAVE_SYS_WAIT_H
#cmakedefine01 HAVE_ASSERT_H
#cmakedefine01 HAVE_STDLIB_H
#cmakedefine01 HAVE_STRING_H
#cmakedefine01 HAVE_INTTYPES_H
#cmakedefine01 HAVE_SYS_TIMES_H
#cmakedefine01 HAVE_SYSCONF
#cmakedefine01 HAVE_STDINT_H
#cmakedefine01 HAVE_STDDEF_H
#cmakedefine01 STDC_HEADERS

#define PACKAGE "@CMAKE_PROJECT_NAME@"
#define PACKAGE_NAME "@CMAKE_PROJECT_NAME@"
#define PACKAGE_STRING "@CMAKE_PROJECT_NAME@ @CMAKE_PROJECT_VERSION@"
#define PACKAGE_VERSION "@CMAKE_PROJECT_VERSION@"

#define SIZEOF_INT @SIZEOF_INT@
#define SIZEOF_LONG @SIZEOF_LONG@
#define SIZEOF_LONG_DOUBLE @SIZEOF_LONG_DOUBLE@
#define SIZEOF_VOID_P @SIZEOF_VOID_P@

#cmakedefine WORDS_BIGENDIAN

